### PR TITLE
small changes to makefile and documentation

### PR DESCRIPTION
**Pull request by devopsec**
add copying swift include headers to Makefile.in, update documentation to include some common configuration issue resolutions

### CODE REVIEW

**Comment by jkister** [comment]
can you explain why chan_oss and/or chan_alsa is needed ?  I dont have them in asterisk13, all seems fine.

in addition, i dont have libasound2-dev, alsa-base, alsa-utils, nor alsa-oss.  is there something you can add to the documentation to describe when these modules are needed ?

**Comment by devopsec** [comment]
Cepstral had some clients that were running into issues with bad output audio using app_swift on various versions of Asterisk 13. We did some investigating and weren't able to find any issue with buffering as we initially thought, but found that the chan_oss / chan_alsa drivers seemed to fix the issue.

Thought it would be worth noting in your the documentation, or perhaps put it in a seperate FAQ document, with answers to common issues like this.

**Comment by danardf** [comment]
Hi  everybody.

I sucessfully installed app_swift, but i'm not able to hear the message.
I'm using Freepbx 14 / Asterisk 13. (64bits) 

During call, i get these traces.
```
-- Executing [290@from-internal:3] Set("SCCP/102-00000003", "SWIFT_VOICE=Jean-Pierre-8kHz") in new stack
-- Executing [290@from-internal:4] Swift("SCCP/102-00000003", "Il est temps de partir a l'école") in new stack
[2018-06-19 21:03:38] DEBUG[5645][C-00000001]: app_swift.c:366 app_exec: Text to Speak : Il est temps de partir a l'école
[2018-06-19 21:03:38] DEBUG[5645][C-00000001]: app_swift.c:417 app_exec: Config voice is Jean-Pierre-8kHz via swift.conf
[2018-06-19 21:03:38] DEBUG[5645][C-00000001]: app_swift.c:422 app_exec: Config voice override to Jean-Pierre-8kHz via SWIFT_VOICE
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:188 swift_cb: audio callback
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:222 swift_cb: audio easy write, 65535 avail to end 65535 totalavail
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:188 swift_cb: audio callback
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:222 swift_cb: audio easy write, 63487 avail to end 63487 totalavail
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:188 swift_cb: audio callback
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:222 swift_cb: audio easy write, 61439 avail to end 61439 totalavail
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:188 swift_cb: audio callback
[2018-06-19 21:03:38] DEBUG[5646]: app_swift.c:222 swift_cb: audio easy write, 59391 avail to end 59391 totalavail
[2018-06-19 21:03:38] DEBUG[5645][C-00000001]: app_swift.c:502 app_exec: Easy read; 20 bytes and 65535 at end, 57343 free
[2018-06-19 21:03:38] DEBUG[5645][C-00000001]: app_swift.c:536 app_exec: wrote a frame of 20
```

So no sound here.
Could you help me please?

**Comment by patrickdexter** [comment]
Had another customer run into this issue. Pointed them to this pull request and it resolved their issues with Asterisk 13. Merge into the main branch?

**Comment by danardf** [comment]
I've had no sound when the message was reading, and next i enabled chan_sip.so.
All works fine right now.
however, maybe it could be great to improve this app for avoid to load anything else. ;)

**Pull request merged**
